- id: modification-timekeeper
  name: Keep modification times up to date
  description: |
    This hook makes sure that the modification time in the front matter of Markdown files is up to date.
  entry: modification-timekeeper
  language: python
  types: [markdown]
